# Comment
strips:
  pixels:
    pixel_count: 10
    driver_type: Visualizer
  others:
    pixel_count: 12
    driver_type: Dummy
    is_disabled: False
    disabled_pixels: 1, 2, 10-11

runners:
#  first:
#    plugin_type: jira
#    jira_url: http://localhost:8080/api
#    target_strip: pixels
#    led: 0
  test1:
    plugin_type: TestPlugin
    target_strip: pixels
    led: 2
    schedule:
      type: cron
      second: "*/2"
  test2:
    plugin_type: TestPlugin
    target_strip: pixels
    led: 1
    schedule:
      type: interval
      minutes: 1