# Comment
strips:
  ### This section is where we configure the attached LED strips.
  ### Each section name corresponds to the url endpoint.
  ### Each strip also supports is_disabled, disabled_pixels and is_reversed
  visualizer:
    pixel_count: 10
    driver_type: Visualizer

runners:
#  jenkins:
#    plugin_type: jenkins
#    job_url: http://jenkins.example.com/job/MyJob/
#    target_strip: pixels
#    led: 2
#    schedule:
#      type: interval
#      seconds: 2
#  first:
#    plugin_type: jira
#    jira_url: http://localhost:8080/api
#    target_strip: pixels
#    led: 0
#  test1:
#    plugin_type: TestPlugin
#    target_strip: pixels
#    led: 2
#    schedule:
#      type: cron
#      second: "*/2"
#  test2:
#    plugin_type: TestPlugin
#    target_strip: pixels
#    led: 1
#    schedule:
#      type: interval
#      minutes: 1
